apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secret-agency-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-secret-agency
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}