apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-agency-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  spring-datasource-url: {{ .Values.secrets.spring.datasourceUrl | b64enc | quote }}
  spring-nats-url: {{ .Values.secrets.spring.natsUrl | b64enc | quote }}