apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-secret-agency
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-secret-agency
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-secret-agency
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Values.dependencies.mysqlServiceName }}; do echo waiting for mysql; sleep 2; done;']
        - name: wait-for-nats
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Values.dependencies.natsServiceName }}; do echo waiting for nats; sleep 2; done;']
      containers:
        - name: secret-agency
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-agency-secrets
                  key: spring-datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-agency-secrets
                  key: spring-datasource-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-agency-secrets
                  key: spring-datasource-password
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-agency-secrets
                  key: spring-nats-url