replicaCount: 1
image:
  repository: secret-agency-message-service-image
  tag: "latest"
  pullPolicy: Never
service:
  type: LoadBalancer
  port: 8080
namespace: default

dependencies:
  mysqlServiceName: "mysql-service"
  natsServiceName: "nats-service"

secrets:
  spring:
    datasourceUrl: "jdbc:mysql://mysql-service:3306/mydb"
    datasourceUser: "user"
    datasourcePassword: "password"
    natsUrl: "nats://nats-service:4222"