replicaCount: 1
image:
  repository: secret-agency-message-service-image
  tag: "latest"
  pullPolicy: Never
service:
  type: LoadBalancer
  port: 8080
namespace: secret-agency

dependencies:
  mysqlServiceName: "secret-agency-mysql-service"
  natsServiceName: "secret-agency-nats-service"

secrets:
  spring:
    datasourceUrl: "jdbc:mysql://secret-agency-mysql-service.secret-agency.svc.cluster.local:3306/mydb"
    datasourceUser: "user"
    datasourcePassword: "password"
    natsUrl: "nats://secret-agency-nats-service:4222"