version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - 'NATS_SERVER_NAME=nats-server'
      - 'NATS_USER=your-user'
      - 'NATS_PASSWORD=your-password'

  secret-agency-message-service:
    image: secret-agency-message-service-image
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      nats-server:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      NATS_URL: nats://nats-server:4222
