mysql:
  replicaCount: 1
  service:
    type: ClusterIP
  persistence:
    size: "100Mi"
  secrets:
    database: "mydb"
    user: "user"
    password: "password"
    rootpassword: "rootpassword"

nats:
  replicaCount: 1
  service:
    type: ClusterIP
  secrets:
    serverName: "nats-server"
    user: "natsuser"
    password: "natspass"

secret-agency:
  replicaCount: 1
  service:
    type: LoadBalancer
  dependencies:
    mysqlServiceName: "{{ .Release.Name }}-mysql-service"
    natsServiceName: "{{ .Release.Name }}-nats-service"
  secrets:
    spring:
      datasourceUrl: "jdbc:mysql://{{ .Release.Name }}-mysql-service:3306/mydb"
      datasourceUser: "user"
      datasourcePassword: "password"
      natsUrl: "nats://{{ .Release.Name }}-nats-service:4222"