apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nats-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  server-name: {{ .Values.secrets.serverName | b64enc | quote }}
  user: {{ .Values.secrets.user | b64enc | quote }}
  password: {{ include "nats.user-password" . }}