apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Release.Name }}-nats-service"
    nginx.ingress.kubernetes.io/backend-protocol: "WS"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: nats.api.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nats-service
                port:
                  number: {{ .Values.service.ports.websocket | default 9222 }}
  tls:
    - hosts:
        - nats.api.your-domain.com
      secretName: {{ .Release.Name }}-nats-tls