apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: default
spec:
  selector:
    app: nats-server
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  type: ClusterIP