replicaCount: 1
image:
  repository: nats
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    client: 4222
    monitoring: 8222
namespace: secret-agency

secrets:
  serverName: "nats-server"
  user: "natsuser"
  password: "natspass"