apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  database-name: {{ .Values.secrets.database | b64enc | quote }}
  user: {{ .Values.secrets.user | b64enc | quote }}
  password: {{ include "db.user-password" . | b64enc | quote }}
  rootpassword: {{ include "db.root-password" . | b64enc | quote }}