apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  database-name: {{ .Values.secrets.database | b64enc | quote }}
  user: {{ .Values.secrets.user | b64enc | quote }}
  password: {{ .Values.secrets.password | b64enc | quote }}
  rootpassword: {{ .Values.secrets.rootpassword | b64enc | quote }}