apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nats-config
  namespace: {{ .Values.namespace }}
data:
  nats.conf: |
    # NATS Server Configuration
    listen: 0.0.0.0:{{ .Values.service.ports.client }}
    http: 0.0.0.0:{{ .Values.service.ports.monitoring }}
    websocket {
      port: {{ .Values.service.ports.websocket }}
      no_tls: true  # Set to false if you want to enable TLS for WebSocket
      # Optional: compression = true  # Enable WebSocket compression
    }