apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-agency
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-agency
  template:
    metadata:
      labels:
        app: secret-agency
    spec:
#      initContainers:
#        - name: wait-for-mysql
#          image: busybox
#          command: ['sh', '-c', 'until nslookup mysql-service; do echo waiting for mysql; sleep 2; done;']
#        - name: wait-for-nats
#          image: busybox
#          command: ['sh', '-c', 'until nslookup nats-service; do echo waiting for nats; sleep 2; done;']
      containers:
        - name: secret-agency
          image: secret-agency-message-service-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-agency-secrets
                  key: spring-datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-agency-secrets
                  key: spring-datasource-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-agency-secrets
                  key: spring-datasource-password
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: secret-agency-secrets
                  key: spring-nats-url