apiVersion: v1
kind: Service
metadata:
  name: secret-agency-service
  namespace: default
spec:
  selector:
    app: secret-agency
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer