apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-agency
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-agency
  template:
    metadata:
      labels:
        app: secret-agency
    spec:
#      initContainers:
#        - name: wait-for-mysql
#          image: busybox
#          command: ['sh', '-c', 'until nslookup mysql-service; do echo waiting for mysql; sleep 2; done;']
#        - name: wait-for-nats
#          image: busybox
#          command: ['sh', '-c', 'until nslookup nats-service; do echo waiting for nats; sleep 2; done;']
      containers:
        - name: secret-agency
          image: secret-agency-message-service-image:latest
          imagePullPolicy: Never  # Если образ локальный
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/mydatabase"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: NATS_URL
              value: "nats://nats-service:4222"