version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - 'NATS_SERVER_NAME=${NATS_SERVER_NAME}'
      - 'NATS_USER=${NATS_USER}'
      - 'NATS_PASSWORD=${NATS_PASSWORD}'

  secret-agency-message-service:
    image: secret-agency-message-service-image
    build:
      context: .
      dockerfile: charts/docker/Dockerfile
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      nats-server:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - NATS_URL=${NATS_URL}
