apiVersion: v2
name: secret-agency-service
description: A Helm chart for Secret agency message service app
version: 0.1.0
dependencies:
  - name: nats
    version: "0.1.0"
    repository: "file://charts/nats-server"
  - name: mysql
    version: "0.1.0"
    repository: "file://charts/mysql"
    condition: mysql.enabled
  - name: secret-agency
    version: "0.1.0"
    repository: "file://charts/secret-agency"
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"