controller:
  service:
    ports:
      http: 80
      https: 443
      mysql: 3306
      nats: 4222
      nats-monitoring: 8222
      nats-routing: 9222
    targetPorts:
      mysql: 3306
      nats: 4222
      nats-monitoring: 8222
      nats-routing: 9222
  tcp:
    3306: "secret-agency/secret-agency-mysql-service:3306"
    4222: "secret-agency/secret-agency-nats-service:4222"
    8222: "secret-agency/secret-agency-nats-service:8222"
    9222: "secret-agency/secret-agency-nats-service:9222"